### ISSUE TITLE
Broken since updating to 1.4.0.4 (during database migration??)

### ISSUE THREAD

**Issue by Perrin-the-wolf** [Catfriend1/syncthing-android#621]
Since updating to 1.4.0.4 syncthing-fork is always shutting down. It seems there are errors in migrating the database (see attached log). The mentioned pictures are,since long ago, not on my mobile anymore. 
I don't understand other error 'another instance may be already running' since it's the only session.
If I remove and install the app it's working as long as I don't import my settings... 

```
23:23:08 [start] INFO: syncthing v1.4.0 "Fermium Flea" (go1.13 android-arm64) vagrant@basebox-stretch64 2020-03-06 19:52:22 UTC
23:23:10 [start] INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
23:23:10 [GMFW6] INFO: My ID: 12345-67890-blahblah-blah-blah-blah
23:23:11 [GMFW6] INFO: Single thread SHA256 performance is 1446 MB/s using crypto/sha256 (1374 MB/s using minio/sha256-simd).
23:23:11 [GMFW6] INFO: Hashing performance is 593.53 MB/s
23:23:11 [GMFW6] INFO: Migrating database to schema version 9...
23:26:29 [GMFW6] WARNING: Database schema: leveldb/table: Writer: keys are not in increasing order: "\x01\x00\x00\x00\x00Camera/IMG_20181226_190237.jpg\x01\t\xe0h\x00\x00\x00\x00", "\x01\x00\x00\x00\x00Camera/IMG_20181226_160004.jpg\x01w\x92\x12\x00\x00\x00\x00"
23:26:29W/SyncthingRunnable exit reason = exitError. Another Syncthing instance may be already running.
23:26:29I/SyncthingService onServiceStateChange: from ERROR to DISABLED
23:26:29I/Util     runShellCommandGetOutput: Exited with code 0
23:26:29W/ApiRequest Request to https://127.0.0.1:8384/rest/system/shutdown failed, java.net.ConnectException: Failed to connect to /127.0.0.1:8384
23:26:36I/Util     runShellCommandGetOutput: Exited with code 0

```

**Comment by Catfriend1** [comment]
Hi,

I recall from the Syncthing Forum there was a database migration glitch fixed in the current v1.4.1-rc.3 candidate. You could try to import your settings, force close the app and then upgrade to v1.4.1-rc.3 via Google Play BETA channel or the GitHub APK download.

If that doesn't work, you might have found a new bug in SyncthingNative's DB migration. Please ZIP up your log and settings export (which includes the database) and ask on the forum.syncthing.net whom of the developers you could send it in privately.

Kind regards

**Comment by Catfriend1** [comment]
See my post in : https://forum.syncthing.net/t/panic-non-increasing-sequence/14570/111?u=catfriend1

**Comment by Perrin-the-wolf** [comment]
Thanks for the fast reply. 
I installed your version and the error persists 

```
23:59:25 INFO: Device ID: D6W5DQE-QOK3LDQ-XZBARDJ-VJZ63JQ-SANL6W5-X6E33HV-DOZOL6H-GYFPIAQ
23:59:25 INFO: Default folder created and/or linked to new config
23:59:26 D6W5DQE-QOK3LDQ-XZBARDJ-VJZ63JQ-SANL6W5-X6E33HV-DOZOL6H-GYFPIAQ
23:59:28 [start] INFO: syncthing v1.4.1-preview.3 "Fermium Flea" (go1.13.9 android-arm64) CF\Anwender@NETSRV 2020-03-20 11:07:29 UTC
23:59:28 [D6W5D] INFO: My ID: D6W5DQE-QOK3LDQ-XZBARDJ-VJZ63JQ-SANL6W5-X6E33HV-DOZOL6H-GYFPIAQ
23:59:29 [D6W5D] INFO: Single thread SHA256 performance is 1410 MB/s using crypto/sha256 (1310 MB/s using minio/sha256-simd).
23:59:29 [D6W5D] INFO: Hashing performance is 629.72 MB/s
23:59:29 [D6W5D] INFO: Migrating database to schema version 1...
23:59:29 [D6W5D] INFO: Migrating database to schema version 2...
23:59:29 [D6W5D] INFO: Migrating database to schema version 3...
23:59:29 [D6W5D] INFO: Migrating database to schema version 5...
23:59:29 [D6W5D] INFO: Migrating database to schema version 6...
23:59:29 [D6W5D] INFO: Migrating database to schema version 7...
23:59:29 [D6W5D] INFO: Migrating database to schema version 9...
23:59:29 [D6W5D] INFO: Compacting database after migration...
23:59:29 [D6W5D] INFO: Checking db due to upgrade - this may take a while...
23:59:29 [D6W5D] INFO: Starting deadlock detector with 20m0s timeout
23:59:29 [D6W5D] INFO: Overall send rate is unlimited, receive rate is unlimited
23:59:29 [D6W5D] INFO: No stored folder metadata for "poco_f1_z4tj-Bilder"; recalculating
23:59:29 [D6W5D] INFO: Using discovery server https://discovery.syncthing.net/v2/?noannounce&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
23:59:29 [D6W5D] INFO: Using discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
23:59:29 [D6W5D] INFO: Using discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
23:59:29 [D6W5D] INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
23:59:29 [D6W5D] INFO: QUIC listener ([::]:22000) starting
23:59:29 [D6W5D] INFO: TCP listener ([::]:22000) starting
23:59:29 [D6W5D] INFO: Ready to synchronize "Android Kamera" (poco_f1_z4tj-Bilder) (sendonly)
23:59:29 [D6W5D] INFO: Loading HTTPS certificate: open /data/user/0/com.github.catfriend1.syncthingandroid.debug/files/https-cert.pem: no such file or directory
23:59:29 [D6W5D] INFO: Creating new HTTPS certificate
23:59:29 [D6W5D] INFO: GUI and API listening on 127.0.0.1:8384
23:59:29 [D6W5D] INFO: Access the GUI via the following URL: https://127.0.0.1:8384/
23:59:29 [D6W5D] INFO: My name is "POCO F1"
23:59:36 [D6W5D] INFO: QUIC listener ([::]:22000) shutting down
23:59:36 [D6W5D] INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
23:59:36 [D6W5D] INFO: Failed initial scan of sendonly folder "Android Kamera" (poco_f1_z4tj-Bilder)
23:59:36 [D6W5D] INFO: Detected 1 NAT service
23:59:36 [D6W5D] INFO: TCP listener ([::]:22000) shutting down
23:59:36 [D6W5D] INFO: Exiting
23:59:40 1234567890-MN6XXRI-54ZJR55-RVMRE7O-P2IQFEB-OGAQAY3-IH4O3JE-N4TXDQX
23:59:55 [start] INFO: syncthing v1.4.1-preview.3 "Fermium Flea" (go1.13.9 android-arm64) CF\Anwender@NETSRV 2020-03-20 11:07:29 UTC
00:00:05 [start] INFO: syncthing v1.4.1-preview.3 "Fermium Flea" (go1.13.9 android-arm64) CF\Anwender@NETSRV 2020-03-20 11:07:29 UTC
00:00:05 [GMFW6] INFO: My ID: 1234567890-MN6XXRI-54ZJR55-RVMRE7O-P2IQFEB-OGAQAY3-IH4O3JE-N4TXDQX
00:00:06 [GMFW6] INFO: Single thread SHA256 performance is 1368 MB/s using crypto/sha256 (1343 MB/s using minio/sha256-simd).
00:00:07 [GMFW6] INFO: Hashing performance is 597.79 MB/s
00:00:07 [GMFW6] INFO: Migrating database to schema version 9...
00:01:31 [GMFW6] WARNING: Database schema: leveldb/table: Writer: keys are not in increasing order: "\x01\x00\x00\x00\x00Camera/IMG_20181226_190237.jpg\x01\t\xe0h\x00\x00\x00\x00", "\x01\x00\x00\x00\x00Camera/IMG_20181226_160004.jpg\x01w\x92\x12\x00\x00\x00\x00"
```

**Comment by Perrin-the-wolf** [comment]
So it looks like my database is broken (don't know why) and I would close this issue...

**Comment by Catfriend1** [comment]
I guess imsodin might be interested to analyze the broken database...
