### ISSUE TITLE
App doesn't show folder-share requests from other devices, except in Web GUI

### ISSUE THREAD

**Issue by nyanpasu64** [Catfriend1/syncthing-android#702]
### Description of the issue

If another device (like a PC) tries to share a folder with Syncthing-Fork on Android, the app doesn't prompt the user that the folder is available for download. You only receive the prompt once you open the Web GUI (which doesn't work on my tablet's LineageOS without GApps, until I install Bromite WebView).

### Reproducer

- Connect Syncthing-Fork on Android, and Syncthing on a PC.
- On the PC, click a folder, click Edit, and on the Sharing tab, check Syncthing-Fork.
- On Android, wait to receive the folder. It'll never arrive.

### Version Information
    App Version: 1.8.0.3
    Syncthing Version: v1.8.0
    Android Version: Android 9 (LineageOS custom ROM)
    Device manufacturer: Samsung
    Device model: SM-T510

### Device platform info

```
[ro.product.board]: [universal7885]
[ro.product.brand]: [Android]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.device]: [phhgsi_a64_ab]
[ro.product.first_api_level]: [28]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [unknown]
[ro.product.model]: [Phh-Treble vanilla]
[ro.product.name]: [treble_a64_bvN]
[ro.product.vendor.brand]: [samsung]
[ro.product.vendor.device]: [gta3xlwifi]
[ro.product.vendor.manufacturer]: [samsung]
[ro.product.vendor.model]: [SM-T510]
[ro.product.vendor.name]: [gta3xlwifixx]
```

### Android Log

https://gist.githubusercontent.com/nyanpasu64/a8eb8b8ff0abbc13aafbf49761dbd8e6/raw/79b253a43c4801e5a96666c7cf071d0e7c85d3af/syncthing-android%2520logcat

The relevant line is here:

> 2020-08-28 06:50:10.379 18501-18545/com.github.catfriend1.syncthingandroid I/SyncthingNativeCode: [COKI3] INFO: **Unexpected folder "ebooks" (7hcwu-pzhhi) sent from device "HCFGYJX-4NRX73J-PSS6UHS-IPEUZVG-MXUK6YN-O7ZLSCB-NZGZQML-J4ZYLQV"; ensure that the folder exists and that this device is selected under "Share With" in the folder configuration.**

When I open the web GUI, I get the following logcat without anything interesting: https://gist.githubusercontent.com/nyanpasu64/a8eb8b8ff0abbc13aafbf49761dbd8e6/raw/33e73e62558ce0907cc71aafb55b2f2b947ec2a3/open%2520web%2520gui

**Comment by Catfriend1** [comment]
Hi thanks for your detailed report. I guess you already know that syncthing needs to be running (green light) for this to work. What you could try is updating to the most recent 1.9.0.x release from the github release page. I've fixed a bug in the event listener a few days ago.

**Comment by nyanpasu64** [comment]
I don't see any difference in v1.9.0.1; I still get an incoming folder notification in the web GUI but none in the app. The Devices tab says "Up to Date" and the Folders tab has no indication of incoming folders. Is this feature broken, or was it never added into the Android interface?

**Comment by Catfriend1** [comment]
Notifications should go to Android's notification bar. Is it suppressed somehow?

**Comment by Catfriend1** [comment]
Closed due to inactivity. For me it works!

**Comment by Pfeil** [comment]
While the App has been working fine for months now, I now also experience this issue. Not sure, but it could have been one of the latest app updates. All kinds of notifications are allowed according to the Android Settings. Before I come to the basic infos, here the ones I think might be interesting:

> 17:03:37 [AJZIL] INFO: Ignoring folder "Audiobooks" ($ID-gekoy) from device $ID-5IRTPAV since we are configured to
17:03:37 [AJZIL] INFO: Established secure connection to $ID-3OTY6QU at [$IP:34c9]:22000-[$IP:cddb]:22000/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256
17:03:37 [AJZIL] INFO: Device $ID-3OTY6QU client is "syncthing v1.12.0" named "$G" at [$IP:34c9]:22000-[$IP:cddb]:22000/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256
17:03:37 [AJZIL] INFO: Unexpected folder "test" ($ID-xcxom) sent from device "$ID-3OTY6QU"; ensure that the folder exists and that this device is selected under "Share With" in the folder configuration.
17:03:37 [AJZIL] INFO: Unexpected folder "Audiobooks" ($ID-gekoy) sent from device "$ID-3OTY6QU"; ensure that the folder exists and that this device is selected under "Share With" in the folder configuration.

Notes:

- The first lines end was not cut off my be, this is what the log within the App is showing.
- I am a bit paranoid and therefore did those $ID/$IP shortcuts. I can also give the full log, but as I have a server which uses it's hostname/domain as name, I wanted to avoid posting it without cleaning to ensure crawlers do not annoy it too much. I can do that though if you think it might help.
- As you can see there are two folders, "test" and "Audiobooks". The latter was first named "Hörbücher" but I choose to translate the name to see if it was some UTF error kind of thing. Then, I shared a completely new and empty folder named "test". As you can see, it also does not work.
- But as you can see, there seems to be a difference in the error messages depending on which peer is sharing. 5IRTPAV is running on an ARM server (a Rasperry Pi 4 running yunohost), while 3OTY6QU is running on an intel i7 processor (desktop machine).
- I haven't tried reinstalling the app yet, only rebooting etc.

### Version Information
    App Version: 1.12.0.1 (from the F-Droid Store)
    Syncthing Version: v1.12.0
    Android Version: Android 10 (Android One)
    Device manufacturer: Nokia
    Device model: Nokia 7.2

About those:
    adb shell "getprop | grep ro.product"
    adb logcat v
    or MatLog (search on GitHub) output

I assume I would have to root my device to do that or something? I would need some time to look into this, if you think it is helpful. I'd like to avoid rooting, though. But I can provide the full in-app logs within the next few days.

**Comment by Catfriend1** [comment]
Please try Settings > Syncthing Options > Un-ignore folders and devices.

**Comment by Pfeil** [comment]
Sorry I must have overseen that setting. This worked. Thanks :)

**Comment by Catfriend1** [comment]
No problem, I hope this thread helps other users if they have the same symptom.

**Comment by nyanpasu64** [comment]
> Notifications should go to Android's notification bar. Is it suppressed somehow?

Initially I didn't see the notification. In a later attempt at adding devices, I did get the notification. Not sure what's going on, I haven't used Syncthing-Fork or added folders in months.

**Comment by Catfriend1** [comment]
@nyanpasu64 Which discovery methods do you use for connecting devices?

**Comment by nyanpasu64** [comment]
On Syncthing-Fork, I didn't change the discovery methods from the default. NAT traversal, local discovery, global discovery, and relaying are all checked in the app. I don't know about on my PC though.

**Comment by Catfriend1** [comment]
ok, the point is, "Internet global" discovery takes a long time to connect my devices when I try this here. maybe local connection or static ip is faster.
